disease_descriptions = {
    '(vertigo) Paroxysmal Positional Vertigo': 'Vertigo is a condition characterized by dizziness and a sensation of spinning. Paroxysmal positional vertigo is a type of vertigo triggered by specific head movements.',
    'AIDS': 'AIDS (Acquired Immunodeficiency Syndrome) is a late stage of HIV (Human Immunodeficiency Virus) infection. It weakens the immune system, making the body susceptible to various infections and diseases.',
    'Acne': 'Acne is a common skin condition that causes pimples, blackheads, and whiteheads. It often occurs during adolescence due to hormonal changes.',
    'Alcoholic hepatitis': 'Alcoholic hepatitis is inflammation of the liver caused by excessive alcohol consumption. It can lead to liver damage and scarring.',
    'Allergy': 'Allergy is an immune system response to a foreign substance (allergen) that is not typically harmful. Symptoms may include sneezing, itching, and skin rashes.',
    'Arthritis': 'Arthritis is a group of conditions that cause joint inflammation, pain, and stiffness. There are various types of arthritis, including osteoarthritis and rheumatoid arthritis.',
    'Bronchial Asthma': 'Bronchial asthma is a chronic respiratory condition that causes airway inflammation and constriction, leading to difficulty breathing and wheezing.',
    'Cervical spondylosis': 'Cervical spondylosis is a degenerative condition of the cervical spine (neck). It can cause neck pain, stiffness, and sometimes numbness or weakness in the arms.',
    'Chicken pox': 'Chickenpox is a contagious viral infection characterized by an itchy rash and flu-like symptoms. It is caused by the varicella-zoster virus.',
    'Chronic cholestasis': 'Chronic cholestasis is a condition in which bile flow from the liver to the small intestine is impaired, leading to the buildup of bile in the liver. It can cause jaundice and liver damage.',
    'Common Cold': 'The common cold is a viral infection of the upper respiratory tract. Symptoms include a runny or stuffy nose, sneezing, coughing, and a sore throat.',
    'Dengue': 'Dengue is a mosquito-borne viral infection that causes flu-like symptoms, including high fever, severe joint and muscle pain, and rash.',
    'Diabetes': 'Diabetes is a chronic condition that affects blood sugar levels. There are two main types: type 1 (insulin-dependent) and type 2 (non-insulin-dependent). It can lead to various complications if not managed properly.',
    'Dimorphic hemorrhoids (piles)': 'Hemorrhoids, also known as piles, are swollen blood vessels in the rectum or anus. They can cause pain, bleeding, and discomfort.',
    'Drug Reaction': 'Drug reactions can occur as adverse side effects to medications. They can vary in severity and may include skin rashes, allergies, or more serious reactions.',
    'Fungal infection': 'Fungal infections are caused by fungi and can affect various parts of the body, including the skin, nails, and respiratory system.',
    'GERD (Gastroesophageal Reflux Disease)': 'GERD is a chronic digestive disorder in which stomach acid flows back into the esophagus, causing heartburn and irritation of the esophagus lining.',
    'Gastroenteritis': 'Gastroenteritis is an inflammation of the stomach and intestines, often caused by viral or bacterial infections. Common symptoms include diarrhea, vomiting, and abdominal pain.',
    'Heart attack': 'A heart attack, or myocardial infarction, occurs when blood flow to the heart muscle is blocked, leading to heart muscle damage. Symptoms include chest pain and shortness of breath.',
    'Hepatitis B': 'Hepatitis B is a viral infection that affects the liver. It can be acute or chronic and may lead to liver damage. It is transmitted through contact with infected blood or body fluids.',
    'Hepatitis C': 'Hepatitis C is a viral infection of the liver that can lead to chronic liver disease. It is transmitted through contact with infected blood.',
    'Hepatitis D': 'Hepatitis D is a viral infection that can only occur in individuals already infected with hepatitis B. It can lead to severe liver damage.',
    'Hepatitis E': 'Hepatitis E is a viral infection of the liver typically transmitted through contaminated water or food. It is usually self-limiting but can be severe in some cases.',
    'Hypertension (High Blood Pressure)': 'Hypertension is a condition in which the force of blood against the artery walls is too high. It can lead to serious health problems, including heart disease and stroke.',
    'Hyperthyroidism': 'Hyperthyroidism is a condition in which the thyroid gland produces too much thyroid hormone. It can lead to symptoms such as weight loss, rapid heartbeat, and anxiety.',
    'Hypoglycemia': 'Hypoglycemia is a condition characterized by low blood sugar levels. It can cause symptoms such as dizziness, sweating, and confusion.',
    'Hypothyroidism': 'Hypothyroidism is a condition in which the thyroid gland does not produce enough thyroid hormone. It can lead to fatigue, weight gain, and cold intolerance.',
    'Impetigo': 'Impetigo is a contagious skin infection caused by bacteria. It is common in children and is characterized by red sores and blisters on the skin.',
    'Jaundice': 'Jaundice is a yellowing of the skin and eyes due to a buildup of bilirubin in the blood. It can be a symptom of various underlying medical conditions.',
    'Malaria': 'Malaria is a mosquito-borne infectious disease caused by parasites. It leads to recurrent fever, chills, and flu-like symptoms.',
    'Migraine': 'Migraine is a type of headache characterized by severe throbbing pain, usually on one side of the head. It may be accompanied by nausea, vomiting, and sensitivity to light and sound.',
    'Osteoarthritis': 'Osteoarthritis is a degenerative joint disease that causes joint pain and stiffness. It is often associated with aging and wear and tear.',
    'Paralysis (brain hemorrhage)': 'Paralysis resulting from a brain hemorrhage is a loss of muscle function caused by bleeding in the brain. It can lead to varying degrees of paralysis.',
    'Peptic ulcer disease': 'Peptic ulcer disease involves the development of open sores (ulcers) on the lining of the stomach or the duodenum (the first part of the small intestine). It can cause abdominal pain and bleeding.',
    'Pneumonia': 'Pneumonia is a lung infection that can be caused by bacteria, viruses, or fungi. It leads to symptoms such as fever, cough, and difficulty breathing.',
    'Psoriasis': 'Psoriasis is a chronic skin condition characterized by red, scaly patches on the skin. It is an autoimmune disorder.',
    'Tuberculosis': 'Tuberculosis (TB) is a bacterial infection that primarily affects the lungs. It can cause persistent cough, fever, and weight loss.',
    'Typhoid': 'Typhoid fever is a bacterial infection caused by Salmonella typhi. Symptoms include high fever, abdominal pain, and gastrointestinal issues.',
    'Urinary tract infection': 'A urinary tract infection (UTI) is an infection in any part of the urinary system, including the bladder and urethra. It can lead to symptoms such as frequent urination and pain.',
    'Varicose veins': 'Varicose veins are swollen, twisted veins that often occur in the legs. They can cause pain and discomfort.',
    'Hepatitis A': 'Hepatitis A is a viral infection of the liver that is typically transmitted through contaminated food or water. It is usually a self-limiting illness.'
}
feature_importances_data = {'receiving_blood_transfusion': 0.012759,
'red_sore_around_nose': 0.013223,
'abnormal_menstruation': 0.025150,
'continuous_sneezing': 0.013322,
'breathlessness': 0.018282,
'blackheads': 0.021460,
'shivering': 0.011025,
'dizziness': 0.015173,
'back_pain': 0.015733,
'unsteadiness': 0.011627,
'yellow_crust_ooze': 0.013239,
'muscle_weakness': 0.028525,
'loss_of_balance': 0.014713,
'chills': 0.024543,
'ulcers_on_tongue': 0.015526,
'stomach_bleeding': 0.011647,
'lack_of_concentration': 0.015711,
'coma': 0.013402,
'neck_pain': 0.027405,
'weakness_of_one_body_side': 0.008008,
'diarrhoea': 0.018496,
'receiving_unsterile_injections': 0.011771,
'headache': 0.036250,
'family_history': 0.012124,
'fast_heart_rate': 0.020262,
'pain_behind_the_eyes': 0.012951,
'sweating': 0.029392,
'mucoid_sputum': 0.014922,
'spotting_ urination': 0.014582,
'sunken_eyes': 0.008175,
'dischromic _patches': 0.018705,
'nausea': 0.032213,
'dehydration': 0.009839,
'loss_of_appetite': 0.023183,
'abdominal_pain': 0.029517,
'stomach_pain': 0.018175,
'yellowish_skin': 0.024647,
'altered_sensorium': 0.017180,
'chest_pain': 0.029555,
'muscle_wasting': 0.016734,
'vomiting': 0.027799,
'mild_fever': 0.022402,
'high_fever': 0.029028,
'red_spots_over_body': 0.013126,
'dark_urine': 0.018927,
'itching': 0.031445,
'yellowing_of_eyes': 0.023203,
'fatigue': 0.048896,
'joint_pain': 0.036494,
'muscle_pain': 0.025798
}